### GET lights
GET localhost:8080/lights

<> 2025-02-18T232418.200.json
<> 2025-02-18T232308.200.json
<> 2025-02-18T231607.200.json
<> 2025-02-18T231516.200.json
<> 2025-02-18T225419.200.json
<> 2025-02-18T224723.200.json
<> 2025-02-18T205856.200.json
<> 2025-02-18T205811.200.json


### Create Light
POST localhost:8080/lights?name=slow_boy&delay=10000

### Create Light v2
POST localhost:8080/lights
Content-Type: application/json

{
  "name": "fast_2",
  "delay": 3000
}


### Create Light v2_mid
POST localhost:8080/lights
Content-Type: application/json

{
  "name": "mid",
  "delay": 5000
}


### Create Light V2_slow
POST localhost:8080/lights
Content-Type: application/json

{
  "name": "slow",
  "delay": 10000
}


### Delete
DELETE localhost:8080/lights?id=72


###
DELETE http://localhost:8080/lights/1